### ISSUE TITLE
Performance gaps in using GPUs for dask `(X + X.T).sum`

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [Akshay-Venkatesh/ucx-py#106]
Running with 4 workers and CPUs

```
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py
[1558119036.528254] [prm-dgx-34:56888:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-a816a85e-78d4-11e9-9e38-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=4 cores=320>
8.19 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 9.72s
distributed.scheduler - INFO - Remove client Client-a816a85e-78d4-11e9-9e38-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-a816a85e-78d4-11e9-9e38-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-a816a85e-78d4-11e9-9e38-a81e84f29bf5
```

Using 4 GPUs:
```
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py 
[1558119233.787219] [prm-dgx-34:57443:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-1da70ca8-78d5-11e9-a063-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=4 cores=320>
8.19 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 21.60s
distributed.scheduler - INFO - Remove client Client-1da70ca8-78d5-11e9-a063-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-1da70ca8-78d5-11e9-a063-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-1da70ca8-78d5-11e9-a063-a81e84f29bf5
```

1. I want to start by finding out what was the compute time and what was the communication time for the job. Does dask permit getting such metrics?

2. @mrocklin pointed to [this](https://stackoverflow.com/questions/56192119/how-can-i-track-the-bandwidth-of-transfers-within-a-dask-cluster/56192120#56192120) but a more details would be useful. I'm used to using [MPIP](http://mpip.sourceforge.net/) which provides a plethora of metrics about MPI calls. This includes a histogram of top 5 time-consuming calls and their call frequency. Something along those lines, if dask already has them, would be useful.

3. Also want to find out how much `ucx` brings to the table by comparing with dask over `tcp`. Will the latter work when I use cupy objects in dask?

**Comment by Akshay-Venkatesh** [comment]
Another data point with 8-workers:
```shell
# CPU 32k x 32k:
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py
[1558120705.041678] [prm-dgx-34:60319:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-8abe9f68-78d8-11e9-ab9f-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=8 cores=640>
8.19 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 6.45s
distributed.scheduler - INFO - Remove client Client-8abe9f68-78d8-11e9-ab9f-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-8abe9f68-78d8-11e9-ab9f-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-8abe9f68-78d8-11e9-ab9f-a81e84f29bf5

# GPU 32k x 32k
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py 
[1558120742.119400] [prm-dgx-34:60677:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-a0d1f028-78d8-11e9-ad05-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=8 cores=640>
8.19 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 16.62s
distributed.scheduler - INFO - Remove client Client-a0d1f028-78d8-11e9-ad05-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-a0d1f028-78d8-11e9-ad05-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-a0d1f028-78d8-11e9-ad05-a81e84f29bf5

```

```shell 
# CPU 64k x 64k:
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py
[1558120808.561726] [prm-dgx-34:61030:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-c86c6036-78d8-11e9-ae66-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=8 cores=640>
32.77 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 20.06s
distributed.scheduler - INFO - Remove client Client-c86c6036-78d8-11e9-ae66-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-c86c6036-78d8-11e9-ae66-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-c86c6036-78d8-11e9-ae66-a81e84f29bf5

# GPU 64k x 64k:
akvenkatesh@prm-dgx-34:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-dot-prod2.py
[1558120840.310005] [prm-dgx-34:61345:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-db573352-78d8-11e9-afa1-a81e84f29bf5
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://192.168.40.44:13337' processes=8 cores=640>
32.77 GB
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>
        Took 44.70s
distributed.scheduler - INFO - Remove client Client-db573352-78d8-11e9-afa1-a81e84f29bf5
distributed.scheduler - INFO - Remove client Client-db573352-78d8-11e9-afa1-a81e84f29bf5
distributed.scheduler - INFO - Close client connection: Client-db573352-78d8-11e9-afa1-a81e84f29bf5

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     59353      C   /home/akvenkatesh/py/install/bin/python3   10489MiB |
|    0     59386      C   /home/akvenkatesh/py/install/bin/python3     307MiB |
|    1     59370      C   /home/akvenkatesh/py/install/bin/python3   12349MiB |
|    2     59383      C   /home/akvenkatesh/py/install/bin/python3   10489MiB |
|    3     59375      C   /home/akvenkatesh/py/install/bin/python3   12349MiB |
|    4     59385      C   /home/akvenkatesh/py/install/bin/python3   12969MiB |
|    5     59378      C   /home/akvenkatesh/py/install/bin/python3   12845MiB |
|    6     59384      C   /home/akvenkatesh/py/install/bin/python3   12473MiB |
|    7     59352      C   /home/akvenkatesh/py/install/bin/python3   11109MiB |
+-----------------------------------------------------------------------------+
```

**Comment by mrocklin** [comment]
@Akshay-Venkatesh I suspect that short-term the following script may be helpful:

```python
from collections import defaultdict
import asyncio
import cupy
import time
import numpy as np
from pprint import pprint

import dask.array as da
from dask.distributed import Client, wait
from distributed.utils import format_time, format_bytes
from dask_cuda import DGX


async def f():
    async with DGX(asynchronous=True, silence_logs=True) as cluster:
        async with Client(cluster, asynchronous=True) as client:
            rs = da.random.RandomState(RandomState=cupy.random.RandomState)
            x = rs.random((100000, 100000)).persist()

            await wait(x)

            y = (x + x.T).sum()

            result = await client.compute(y)

            incoming_logs = await client.run(lambda dask_worker:
                    dask_worker.incoming_transfer_log)
            bandwidths = defaultdict(list)
            for k, L in incoming_logs.items():
                for d in L:
                    if d['total'] > 1_000_000:
                        bandwidths[k, d['who']].append(d['bandwidth'])
            bandwidths = {
                k: [format_bytes(x) + '/s' for x in np.quantile(v, [0.25, 0.50, 0.75])]
                for k, v in bandwidths.items()
            }
            pprint(bandwidths)


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(f())
```

In gets the incoming transfer logs from each of the workers, and then computes the 25, 50, and 75th percentile of each of the transfers that were great than a megabyte across every pair of workers.  This should give a decent summary of bandwidths that we're seeing, while also giving enough visibility into asymmetry that may exist due to network configuration.

I suspect that you'll want to replace the `DGX` line with a call to `LocalCUDACluster` or `SpecCluster` that matches your testing environment.

**Comment by Akshay-Venkatesh** [comment]
Thanks @mrocklin Will give this a shot today.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin 

Running into a few issues with this program when running outside the context of `dask_cuda`. Made some edits but I see this error ultimately:
```
AttributeError: 'cupy.core.core.ndarray' object has no attribute '__await__'
```
Have I missed something?
```py
import argparse
from time import perf_counter as clock

from collections import defaultdict
import asyncio
import cupy
import time
import numpy as np
from pprint import pprint

import dask.array as da
from dask.distributed import Client, wait
from distributed.utils import format_time, format_bytes
def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--protocol", choices=['ucx', 'tcp', 'inproc'],
                        default="ucx")

    return parser.parse_args(args)


async def main(args=None):
    args = parse_args(args)

    if args.protocol == 'ucx':
        client = Client("ucx://IB-IP:13337")
    elif args.protocol == 'tcp':
        client = Client("tcp://TCP-IP :13337")
    else:
        kwargs = {'n_workers': 2, 'threads_per_worker': 40}
        kwargs['processes'] = args.protocol == 'tcp'
        cluster = LocalCluster(**kwargs)
        client = Client(cluster)

    print(f"Connected to {client}")

    rs = da.random.RandomState(RandomState=cupy.random.RandomState)
    x = rs.random((10000, 10000)).persist()

    y = (x + x.T).sum()

    result = await client.compute(y) # <- error here
    incoming_logs = await client.run(lambda dask_worker:
                                     dask_worker.incoming_transfer_log)
    bandwidths = defaultdict(list)
    for k, L in incoming_logs.items():
        for d in L:
            if d['total'] > 1_000_000:
                bandwidths[k, d['who']].append(d['bandwidth'])

    bandwidths = {
        k: [format_bytes(x) + '/s' for x in np.quantile(v, [0.25, 0.50, 0.75])]
        for k, v in bandwidths.items()
    }
    pprint(bandwidths)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())

```
```shell
akvenkatesh@prm-dgx-02:~/ucx-py$ UCX_RNDV_SCHEME=put_zcopy UCX_MEM_TYPE_CACHE=n python3 tests/dask-print-bw.py 
[1558376521.823080] [prm-dgx-02:11661:0]         parser.c:1437 UCX  WARN  unused env variables: UCX_MEM_TYPE_CACHE, UCX_HOME,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
distributed.scheduler - INFO - Receive client connection: Client-2960b006-7b2c-11e9-ad8d-a81e84f29a99
distributed.core - INFO - Starting established connection
Connected to <Client: scheduler='ucx://IP:13337' processes=8 cores=640>
Traceback (most recent call last):
  File "tests/dask-print-bw.py", line 58, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/home/akvenkatesh/py/install/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "tests/dask-print-bw.py", line 42, in main
    result = await client.compute(y)
  File "/home/akvenkatesh/tom-ucx/distributed/client.py", line 423, in __await__
    return self.result().__await__()
AttributeError: 'cupy.core.core.ndarray' object has no attribute '__await__'
distributed.scheduler - INFO - Remove client Client-2960b006-7b2c-11e9-ad8d-a81e84f29a99
distributed.scheduler - INFO - Remove client Client-2960b006-7b2c-11e9-ad8d-a81e84f29a99
distributed.scheduler - INFO - Close client connection: Client-2960b006-7b2c-11e9-ad8d-a81e84f29a99
```

**Comment by mrocklin** [comment]
You need to pass `asynchronous=True` to `LocalCluster` and `Client`

**Comment by Akshay-Venkatesh** [comment]
@mrocklin Thanks. That gets the benchmark running. Really poor bandwidth by the look of it:

https://gist.github.com/Akshay-Venkatesh/95cb4ba2c9d4684200557563869fd701#file-tmp-txt

**Comment by Akshay-Venkatesh** [comment]
FYI, This is the final program I ended up using:
```py
import argparse
from time import perf_counter as clock

from collections import defaultdict
import asyncio
import cupy
import time
import numpy as np
from pprint import pprint

import dask.array as da
from dask.distributed import Client, wait
from distributed.utils import format_time, format_bytes
def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--protocol", choices=['ucx', 'tcp', 'inproc'],
                        default="ucx")

    return parser.parse_args(args)


async def main(args=None):
    args = parse_args(args)

    if args.protocol == 'ucx':
        client = Client("ucx://IP:13337", asynchronous=True)
    elif args.protocol == 'tcp':
        client = Client("tcp://IP :13337")
    else:
        kwargs = {'n_workers': 2, 'threads_per_worker': 40}
        kwargs['processes'] = args.protocol == 'tcp'
        cluster = LocalCluster(**kwargs)
        client = Client(cluster)
    print(f"Connected to {client}")

    rs = da.random.RandomState(RandomState=cupy.random.RandomState)
    x = rs.random((10000, 10000)).persist()

    y = (x + x.T).sum()

    result = await client.compute(y)
    incoming_logs = await client.run(lambda dask_worker:
                                     dask_worker.incoming_transfer_log)
    bandwidths = defaultdict(list)
    for k, L in incoming_logs.items():
        for d in L:
            if d['total'] > 1_000_000:
                bandwidths[k, d['who']].append(d['bandwidth'])

    bandwidths = {
        k: [format_bytes(x) + '/s' for x in np.quantile(v, [0.25, 0.50, 0.75])]
        for k, v in bandwidths.items()
    }
    pprint(bandwidths)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())

```

**Comment by Akshay-Venkatesh** [comment]
Surprisingly increasing size of `x` to `20k x 20k`, `40k x 40k`, `80k x 80k` doesn't change the bandwidth at all. It's all still in the 200MB range. Checking now with 4 workers instead of 8.

**Comment by Akshay-Venkatesh** [comment]
Working with 2 workers and varying input size between `20k ** 2` and `30 ** 2`. I have the following logs to track send/recv sizes at ucxpy level:

https://gist.github.com/Akshay-Venkatesh/95cb4ba2c9d4684200557563869fd701

Better to download as the logs are large.

**Comment by Akshay-Venkatesh** [comment]
Bottom line for 30k, workers have 17 exchanges of size 107MB:
```shell
akvenkatesh@prm-dgx-01:~/ucx-py/gist-dump$ grep -r 112500000 ucxpy-worker1-30k.log | wc -l
17
akvenkatesh@prm-dgx-01:~/ucx-py/gist-dump$ grep -r 112500000 ucxpy-worker2-30k.log | wc -l
17
```
